{% set version = "0.5.2" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 95c58c194ce657a5f4fb0b9e60a84968c808888aed628cd98ab8771fe1db98ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - botocore >=1.12.36,<2.0a.0

test:
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager
  dev_url: https://github.com/boto/s3transfer

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf
