{% set version = "0.18.0" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 3760b8b7ec1315da54048b2d626276732bee4300d054d492d4e1d43e20d4ecbd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - botocore >=1.37.4,<2.0a.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager
  dev_url: https://github.com/boto/s3transfer

extra:
  recipe-maintainers:
    - tkelman
    - ocefpaf
