{% set version = "0.11.0" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 6563eda054c33bdebef7cbf309488634651c47270d828e594d151cd289fb7cf7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - botocore >=1.33.2,<2.0a.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager
  dev_url: https://github.com/boto/s3transfer

extra:
  recipe-maintainers:
    - tkelman
    - ocefpaf
