{% set version = "0.4.1" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 81b7b3516739b0cfbecaa9077a1baf783e7a790c0e49261fcc6ceda468765efa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3  # Avoid a py2k selector for the futures dependency
    - pip
  run:
    - python >=3
    - botocore >=1.12.36,<2.0a.0

test:
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager
  dev_url: https://github.com/boto/s3transfer

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
