{% set version = "0.6.1" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 640bb492711f4c0c0905e1f62b6aaeb771881935ad27884852411f8e9cacbca9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - botocore >=1.12.36,<2.0a.0

test:
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager
  dev_url: https://github.com/boto/s3transfer

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf
